enhance virtual-manage

diff --git a/virtual-manage b/virtual-manage
--- a/virtual-manage
+++ b/virtual-manage
@@ -24,18 +24,31 @@ DISK_SIZE=10
 TIMEOUT=300
 GRACEFULLY_SHUTDOWN=false
 
-function start {
-    #    docker start docker-dnsmasq
+function start_networks {
     echo -e "\e[32m\e[1m==> Start all inactive networks\e[0m"
 	list_inactive_networks | while read NETWORK; do
-        virsh start $NETWORK | grep -v "^$"
+        if [ ! -z "$NETWORK" ]; then
+            virsh net-start $NETWORK | grep -v "^$"
+        fi
     done
     echo -e "\e[32m\e[1m==> All networks started :) \e[0m"
+}
 
+function shutdown_networks {
+    echo -e "\e[32m\e[1m==> Shutdown all active networks\e[0m"
+	list_running_networks | while read NETWORK; do
+        if [ ! -z "$NETWORK" ]; then
+            virsh net-destroy $NETWORK | grep -v "^$"
+        fi
+    done
+    echo -e "\e[32m\e[1m==> All networks shutdown :) \e[0m"
+}
+
+function start {
     echo -e "\e[32m\e[1m==> Start all inactive domains\e[0m"
 	list_inactive_domains | while read DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
 		        virsh start $DOMAIN | grep -v "^$"
             fi
         done
@@ -46,7 +59,7 @@ function start {
 function status {
 	list_all_domains | while read DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
 		        echo -e "  $DOMAIN   \e[1m\e[92mrunning\e[39m\e[0m"
                 echo -e "  $(virsh dominfo $DOMAIN | grep CPU\(s\))"
                 echo -e "  $(virsh dominfo $DOMAIN | grep 'Max memory')"
@@ -65,7 +78,7 @@ function status {
 function cleanup {
 	list_all_domains | while read DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
                 virsh destroy $DOMAIN
 		        virsh undefine --remove-all-storage $DOMAIN
             fi
@@ -73,10 +86,20 @@ function cleanup {
 	done
 }
 
+function clone {
+    VM_NAME=$1
+
+    if [[ -z $VM_NAME ]]; then
+        echo -en "error: expected syntax: virtual-manage --clone <string>\n\n"
+        exit 0
+    fi
+    virt-clone -o ${VM_NAME} -n ${VM_NAME}_clone -f /var/lib/libvirt/images/${VM_NAME}_clone.qcow2
+}
+
 function acpi_shutdown {
 	list_running_domains | while read DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
 		        virsh shutdown $DOMAIN --mode acpi
             fi
         done
@@ -87,7 +110,7 @@ function power_shutdown {
 	echo -e "==> power shutdown all running KVM domains..."
 	list_running_domains | while read DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
 		        virsh destroy $DOMAIN | grep -v "^$"
 		        # Give libvirt some time for killing off the domain.
 		        sleep 3
@@ -113,7 +136,6 @@ function shutdown {
 	    done
     fi
     power_shutdown
-    sleep 5
     echo -e "\e[33m\e[1m==> All domains shutdown :)\e[0m"
     # list_inactive_domains
 }
@@ -126,38 +148,42 @@ function restart {
 function renew-dhcp {
 	list_all_domains | while read -e DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
                 ssh -n root@${DOMAIN} "nmcli con up id 'System eth0'" 2>&1 > /dev/null
             fi
         done
 	done
 }
 
+function list_running_networks() {
+    virsh net-list --persistent --name
+}
+
 function list_inactive_networks() {
-    virsh -q net-list --inactive | grep "shut off" | awk '{print $2}'
+    virsh net-list --inactive --name
 }
 
 function list_inactive_domains() {
-    virsh -q list --inactive | grep "shut off" | awk '{print $2}'
+    virsh list --inactive --name
 }
 
 function list_running_domains() {
-    virsh -q list | grep "running" | awk '{ print $2}'
+    virsh list --state-running --name
 }
 
 function list_all_domains() {
-    virsh -q list | awk '{ print $2}'
+    virsh list --name
 }
 
 function list_all_snapshots() {
     DOMAIN=$1
-    virsh -q snapshot-list --domain $DOMAIN | awk '{ print $1}'
+    virsh snapshot-list --domain $DOMAIN --name
 }
 
 function add-disk {
 	list_running_domains | while read DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
                 sudo qemu-img create -f qcow2 ${DISK_DIRECTORY}/${DOMAIN}/disk-${DISK_SIZE}.qcow2 ${DISK_SIZE}G
                 virsh attach-disk --domain $DOMAIN --source ${DISK_DIRECTORY}/${DOMAIN}/disk-${DISK_SIZE}.qcow2 --subdriver qcow2 --target vdd --live --cache none
                 echo "Disk added to $DOMAIN domain"
@@ -169,7 +195,7 @@ function add-disk {
 function remove-disk {
 	list_running_domains | while read DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
                 virsh detach-disk --domain $DOMAIN --target vdd --live
                 sudo rm ${DISK_DIRECTORY}/${DOMAIN}/disk-${DISK_SIZE}.qcow2
                 echo "Disk removed from $DOMAIN domain"
@@ -211,7 +237,7 @@ function snap-create {
 
 	list_inactive_domains | while read DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
                 virsh snapshot-create-as --domain $DOMAIN --name $SNAPSHOT_NAME --atomic | egrep -v "^$"
                 echo "Snapshot $SNAPSHOT_NAME create for domain $DOMAIN"
             fi
@@ -264,55 +290,56 @@ function snap-delete {
     shutdown
 	list_inactive_domains | while read DOMAIN; do
         for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
+            if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
                 virsh snapshot-delete $DOMAIN --snapshotname $SNAP_NAME
                 echo "Snapshot $SNAPSHOT_NAME remove for domain $DOMAIN"
-            fi
+                fi
+            done
         done
-    done
-    # start
-}
+        # start
+    }
 
-function snap-revert {
-    SNAP_NAME=$1
+    function snap-revert {
+        SNAP_NAME=$1
 
-    if [[ -z $SNAP_NAME ]]; then
-        echo -en "error: expected syntax: virtual-manage --snap-revert <string>\n\n"
-        echo -en "snapshots:\n"
-        snap-list
-        exit 0
-    fi
-    shutdown
-	list_inactive_domains | while read DOMAIN; do
-        for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
-                virsh snapshot-revert $DOMAIN --snapshotname $SNAP_NAME
-                echo "Snapshot $SNAPSHOT_NAME revert for domain $DOMAIN"
-            fi
+        if [[ -z $SNAP_NAME ]]; then
+            echo -en "error: expected syntax: virtual-manage --snap-revert <string>\n\n"
+            echo -en "snapshots:\n"
+            snap-list
+            exit 0
+        fi
+        shutdown
+	    list_inactive_domains | while read DOMAIN; do
+            for node in $NODE_TYPES; do
+                if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
+                    virsh snapshot-revert $DOMAIN --snapshotname $SNAP_NAME
+                    echo "Snapshot $SNAPSHOT_NAME revert for domain $DOMAIN"
+                fi
+            done
         done
-    done
-    start
-}
+        start
+    }
 
-function snap-list {
-	list_all_domains | while read DOMAIN; do
-        for node in $NODE_TYPES; do
-            if [[ "$DOMAIN" =~ $node ]]; then
-                #                echo -e "\e[33m$DOMAIN [$(virsh snapshot-info $DOMAIN --current | grep Name | cut -d ":" -f2 | sed -e 's/^[ ]*//')]\e[0m"
-                echo -e "$DOMAIN \e[92m\e[1m[$(virsh snapshot-current --name $DOMAIN)]\e[0m"
-                virsh -q snapshot-list --tree --domain $DOMAIN 2>&1
-            fi
+    function snap-list {
+	    list_all_domains | while read DOMAIN; do
+            for node in $NODE_TYPES; do
+                if [[ ! -z "$DOMAIN" && "$DOMAIN" =~ $node ]]; then
+                    #                echo -e "\e[33m$DOMAIN [$(virsh snapshot-info $DOMAIN --current | grep Name | cut -d ":" -f2 | sed -e 's/^[ ]*//')]\e[0m"
+                    echo -e "$DOMAIN \e[92m\e[1m[$(virsh snapshot-current --name $DOMAIN)]\e[0m"
+                    virsh -q snapshot-list --tree --domain $DOMAIN 2>&1
+                fi
+            done
         done
-    done
-}
+    }
 
-function usage {
-    cat <<EOF
+    function usage {
+        cat <<EOF
 Usage: $0 COMMAND
 
 Commands:
     --all                            Start all defined Libvirt VMs
     --cleanup                        Cleanup (destroy & undefine) cluster
+    --clone <VM name>                Clone VM to <VM name>_clone
     --renew-dhcp                     Renew DHCP
     --restart                        Restart cluster
     --start                          Start cluster
@@ -326,82 +353,90 @@ Commands:
     --add-disk <disk size>           Add disk to VMs
     --remove-disk <disk size>        Remove disk from VMs
 EOF
-}
+    }
 
-LONG_OPTS="all,renew-dhcp,cleanup,restart,start,shutdown,status,snap-delete:,snap-create:,snap-revert:,snap-list,add-disk:,remove-disk:,help"
-ARGS=$(getopt -l "${LONG_OPTS}" --name "$0" -- "$@") || { usage >&2; exit 2; }
+    LONG_OPTS="all,clone:,renew-dhcp,cleanup,restart,start,shutdown,status,snap-delete:,snap-create:,snap-revert:,snap-list,add-disk:,remove-disk:,help"
+    ARGS=$(getopt -l "${LONG_OPTS}" --name "$0" -- "$@") || { usage >&2; exit 2; }
 
-while [ "$#" -gt 0 ]; do
-    case "$1" in
-        (--all)
-            ALL_VMS=1
-            shift 1
-            ;;
-        (--cleanup)
-            cleanup
-            exit 0
-            ;;
-        (--restart)
-            restart
-            exit 0
-            ;;
-        (--renew-dhcp)
-            renew-dhcp
-            exit 0
-            ;;
-        (--start)
-            start
-            exit 0
-            ;;
-        (--shutdown)
-            shutdown
-            exit 0
-            ;;
-        (--status)
-            status
-            exit 0
-            ;;
-        (--snap-delete)
-            SNAPSHOT_NAME=$2
-            shift 2
-            snap-delete $SNAPSHOT_NAME
-            exit 0
-            ;;
-        (--add-disk)
-            DISK_SIZE=$2
-            shift 2
-            add-disk
-            exit 0
-            ;;
-        (--remove-disk)
-            DISK_SIZE=$2
-            shift 2
-            remove-disk
-            exit 0
-            ;;
-        (--snap-create)
-            SNAPSHOT_NAME=$2
-            shift 2
-            snap-create $SNAPSHOT_NAME
-            exit 0
-            ;;
-        (--snap-revert)
-            SNAPSHOT_NAME=$2
-            shift 2
-            snap-revert $SNAPSHOT_NAME
-            exit 0
-            ;;
-        (--snap-list)
-            snap-list
-            exit 0
-            ;;
-        (--help|-h)
-            usage
-            exit 0
-            ;;
-        (*)
-            usage
-            exit 3
-            ;;
-    esac
-done
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            (--all)
+                ALL_VMS=1
+                shift 1
+                ;;
+            (--cleanup)
+                cleanup
+                exit 0
+                ;;
+            (--clone)
+                VM_NAME=$2
+                shift 2
+                clone $VM_NAME
+                exit 0
+                ;;
+            (--restart)
+                restart
+                exit 0
+                ;;
+            (--renew-dhcp)
+                renew-dhcp
+                exit 0
+                ;;
+            (--start)
+                start_networks
+                start
+                exit 0
+                ;;
+            (--shutdown)
+                shutdown
+                shutdown_networks
+                exit 0
+                ;;
+            (--status)
+                status
+                exit 0
+                ;;
+            (--snap-delete)
+                SNAPSHOT_NAME=$2
+                shift 2
+                snap-delete $SNAPSHOT_NAME
+                exit 0
+                ;;
+            (--add-disk)
+                DISK_SIZE=$2
+                shift 2
+                add-disk
+                exit 0
+                ;;
+            (--remove-disk)
+                DISK_SIZE=$2
+                shift 2
+                remove-disk
+                exit 0
+                ;;
+            (--snap-create)
+                SNAPSHOT_NAME=$2
+                shift 2
+                snap-create $SNAPSHOT_NAME
+                exit 0
+                ;;
+            (--snap-revert)
+                SNAPSHOT_NAME=$2
+                shift 2
+                snap-revert $SNAPSHOT_NAME
+                exit 0
+                ;;
+            (--snap-list)
+                snap-list
+                exit 0
+                ;;
+            (--help|-h)
+                usage
+                exit 0
+                ;;
+            (*)
+                usage
+                exit 3
+                ;;
+        esac
+    done
